ameliored and changed name of passhandler

diff --git a/.local/scripts/mpm b/.local/scripts/mpm
--- a/.local/scripts/mpm
+++ b/.local/scripts/mpm
@@ -1,5 +1,7 @@
 #!/usr/bin/env bash
 
+
+extract_key() {
 shopt -s nullglob globstar
 
 typeit=0
@@ -24,3 +26,15 @@ else
 	pass show "$password" | { IFS= read -r pass; printf %s "$pass"; } |
 		xdotool type --clearmodifiers --file -
 fi
+}
+
+open_error() {
+  echo "Can't open tomb, try to run pass open -d"
+  sudo swapon -a
+  exit 1
+}
+sudo swapoff -a
+pass open 2>/dev/null || open_error
+extract_key "$1"
+pass close 2>/dev/null || echo "Tomb hasn't been closed properly"
+sudo swapon -a
